### ISSUE TITLE
fix `timeout:  context deadline exceeded`

### ISSUE THREAD

**Issue by otknoy** [otknoy/mflight-api#52]
原因調査から

```
mflight-api_1   | 2021/01/28 02:03:39 timeout:  context deadline exceeded
mflight-api_1   | panic: runtime error: invalid memory address or nil pointer dereference
mflight-api_1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x844090]
mflight-api_1   |
mflight-api_1   | goroutine 13277 [running]:
mflight-api_1   | mflight-api/infrastructure/prometheus/middleware.(*httpRoundTripperMiddleware).RoundTrip(0xc000206000, 0xc000202100, 0xc000206000, 0x0, 0x0)
mflight-api_1   |       /app/infrastructure/prometheus/middleware/client.go:33 +0x190
mflight-api_1   | net/http.send(0xc000202100, 0x9c31c0, 0xc000206000, 0x0, 0x0, 0x0, 0xc000214038, 0xc00034e200, 0x1, 0x0)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:252 +0x453
mflight-api_1   | net/http.(*Client).send(0xc000204030, 0xc000202100, 0x0, 0x0, 0x0, 0xc000214038, 0x0, 0x1, 0xc000206170)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:176 +0xff
mflight-api_1   | net/http.(*Client).do(0xc000204030, 0xc000202100, 0x0, 0x0, 0x0)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:718 +0x45f
mflight-api_1   | net/http.(*Client).Do(...)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:586
mflight-api_1   | mflight-api/infrastructure/mflight.(*client).GetSensorMonitor(0xc000204060, 0x9cba60, 0xc000094060, 0x0, 0x0, 0x0)
mflight-api_1   |       /app/infrastructure/mflight/client.go:48 +0xad
mflight-api_1   | mflight-api/infrastructure/mflight.(*cacheClient).GetSensorMonitor(0xc000200060, 0x9cba60, 0xc000094060, 0x958a48, 0xc0004066c8, 0x83d398)
mflight-api_1   |       /app/infrastructure/mflight/cache.go:28 +0xb3
mflight-api_1   | mflight-api/infrastructure/mflight.(*mfLightSensor).GetMetrics(0xc000206010, 0x9cba60, 0xc000094060, 0xc000406730, 0x4637e0, 0xc00021dc80, 0x3)
mflight-api_1   |       /app/infrastructure/mflight/sensor.go:20 +0x54
mflight-api_1   | mflight-api/application.(*metricsCollector).CollectMetrics(0xc000206020, 0x9cba60, 0xc000094060, 0xc0002a0ba0, 0x3a7919ee, 0xc000222118, 0x440096)
mflight-api_1   |       /app/application/metrics.go:24 +0x47
mflight-api_1   | mflight-api/infrastructure/prometheus/collector.(*collector).Collect.func1(0xc000206040, 0x9cba60, 0xc000094060, 0xc000064120)
mflight-api_1   |       /app/infrastructure/prometheus/collector/mflightcollector.go:64 +0x4b
mflight-api_1   | created by mflight-api/infrastructure/prometheus/collector.(*collector).Collect
mflight-api_1   |       /app/infrastructure/prometheus/collector/mflightcollector.go:63 +0xfc
mflight-api_1   | 2021/01/28 03:18:39 timeout:  context deadline exceeded
mflight-api_1   | panic: runtime error: invalid memory address or nil pointer dereference
mflight-api_1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x844090]
mflight-api_1   |
mflight-api_1   | goroutine 867 [running]:
mflight-api_1   | mflight-api/infrastructure/prometheus/middleware.(*httpRoundTripperMiddleware).RoundTrip(0xc00009c1f0, 0xc000366000, 0xc00009c1f0, 0x0, 0x0)
mflight-api_1   |       /app/infrastructure/prometheus/middleware/client.go:33 +0x190
mflight-api_1   | net/http.send(0xc000366000, 0x9c31c0, 0xc00009c1f0, 0x0, 0x0, 0x0, 0xc00000e028, 0x0, 0x1, 0x0)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:252 +0x453
mflight-api_1   | net/http.(*Client).send(0xc0000a0060, 0xc000366000, 0x0, 0x0, 0x0, 0xc00000e028, 0x0, 0x1, 0xc000218000)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:176 +0xff
mflight-api_1   | net/http.(*Client).do(0xc0000a0060, 0xc000366000, 0x0, 0x0, 0x0)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:718 +0x45f
mflight-api_1   | net/http.(*Client).Do(...)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:586
mflight-api_1   | mflight-api/infrastructure/mflight.(*client).GetSensorMonitor(0xc0000a0090, 0x9cba60, 0xc00025a300, 0x0, 0x0, 0x0)
mflight-api_1   |       /app/infrastructure/mflight/client.go:48 +0xad
mflight-api_1   | mflight-api/infrastructure/mflight.(*cacheClient).GetSensorMonitor(0xc000096b40, 0x9cba60, 0xc00025a300, 0x9c2c40, 0xc0004f0080, 0x0)
mflight-api_1   |       /app/infrastructure/mflight/cache.go:28 +0xb3
mflight-api_1   | mflight-api/infrastructure/mflight.(*mfLightSensor).GetMetrics(0xc00009c200, 0x9cba60, 0xc00025a300, 0xc0000ae8a0, 0xc883a0, 0xc883a0, 0xc883b0)
mflight-api_1   |       /app/infrastructure/mflight/sensor.go:20 +0x54
mflight-api_1   | mflight-api/application.(*metricsCollector).CollectMetrics(0xc00009c210, 0x9cba60, 0xc00025a300, 0xc0000208f8, 0x0, 0x0, 0x440096)
mflight-api_1   |       /app/application/metrics.go:24 +0x47
mflight-api_1   | mflight-api/infrastructure/prometheus/collector.(*collector).Collect.func1(0xc00009c230, 0x9cba60, 0xc00025a300, 0xc0001ac000)
mflight-api_1   |       /app/infrastructure/prometheus/collector/mflightcollector.go:64 +0x4b
mflight-api_1   | created by mflight-api/infrastructure/prometheus/collector.(*collector).Collect
mflight-api_1   |       /app/infrastructure/prometheus/collector/mflightcollector.go:63 +0xfc
mflight-api_1   | panic: runtime error: invalid memory address or nil pointer dereference
mflight-api_1   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x844090]
mflight-api_1   |
mflight-api_1   | goroutine 3963 [running]:
mflight-api_1   | mflight-api/infrastructure/prometheus/middleware.(*httpRoundTripperMiddleware).RoundTrip(0xc00009a000, 0xc00023c300, 0xc00009a000, 0x0, 0x0)
mflight-api_1   |       /app/infrastructure/prometheus/middleware/client.go:33 +0x190
mflight-api_1   | net/http.send(0xc00023c300, 0x9c31c0, 0xc00009a000, 0x0, 0x0, 0x0, 0xc00000e028, 0x0, 0x1, 0x0)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:252 +0x453
mflight-api_1   | net/http.(*Client).send(0xc000098030, 0xc00023c300, 0x0, 0x0, 0x0, 0xc00000e028, 0x0, 0x1, 0xc000228030)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:176 +0xff
mflight-api_1   | net/http.(*Client).do(0xc000098030, 0xc00023c300, 0x0, 0x0, 0x0)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:718 +0x45f
mflight-api_1   | net/http.(*Client).Do(...)
mflight-api_1   |       /usr/local/go/src/net/http/client.go:586
mflight-api_1   | mflight-api/infrastructure/mflight.(*client).GetSensorMonitor(0xc000098060, 0x9cba60, 0xc000021260, 0x0, 0x0, 0x0)
mflight-api_1   |       /app/infrastructure/mflight/client.go:48 +0xad
mflight-api_1   | mflight-api/infrastructure/mflight.(*cacheClient).GetSensorMonitor(0xc000094060, 0x9cba60, 0xc000021260, 0x958a01, 0xc0001caec8, 0x82cd17)
mflight-api_1   |       /app/infrastructure/mflight/cache.go:28 +0xb3
mflight-api_1   | mflight-api/infrastructure/mflight.(*mfLightSensor).GetMetrics(0xc00009a010, 0x9cba60, 0xc000021260, 0xc000020d20, 0xc000021200, 0x0, 0x0)
mflight-api_1   |       /app/infrastructure/mflight/sensor.go:20 +0x54
mflight-api_1   | mflight-api/application.(*metricsCollector).CollectMetrics(0xc00009a020, 0x9cba60, 0xc000021260, 0x0, 0x0, 0xc00020e180, 0xc0001caf38)
mflight-api_1   |       /app/application/metrics.go:24 +0x47
mflight-api_1   | mflight-api/infrastructure/prometheus/collector.(*collector).Collect.func1(0xc00009a040, 0x9cba60, 0xc000021260, 0xc00020e2a0)
mflight-api_1   |       /app/infrastructure/prometheus/collector/mflightcollector.go:64 +0x4b
mflight-api_1   | created by mflight-api/infrastructure/prometheus/collector.(*collector).Collect
mflight-api_1   |       /app/infrastructure/prometheus/collector/mflightcollector.go:63 +0xfc

**Comment by otknoy** [comment]
timeout したときに `res` が nil になるため `res.Status` で panic になるようだ
https://github.com/otknoy/mflight-api/blob/cbf49eef28224947b835ef420fe8b3c01fc531ff/infrastructure/prometheus/middleware/client.go#L22-L36

**Comment by otknoy** [comment]
wrap してる `RoundTrip()` が `nil` を返すテストを書いたら再現した
https://github.com/otknoy/mflight-api/pull/53/commits/f97822a2ddda373c10fe2e953dfadda02acfa91f
https://github.com/otknoy/mflight-api/runs/1784191288
